const eventi = [
  {
    id: 1,
    location: "Milano",
    dataInizio: "2025-10-01",
    dataFine: "2025-10-03",
    operatore: "Luca Rossi",
    status: "pronto",
    partecipanti: [
      {
        nome: "Mario",
        cognome: "Bianchi",
        codiceFiscale: "BNCMRA85T10H501Z",
        email: "mario.bianchi@email.com",
        cellulare: "3331234567",
      },
      {
        nome: "Anna",
        cognome: "Verdi",
        codiceFiscale: "VRDANN90F41H501X",
        email: "anna.verdi@email.com",
        cellulare: "3337654321",
      },
    ],
  },
  {
    id: 2,
    location: "Roma",
    dataInizio: "2025-11-05",
    dataFine: "2025-11-07",
    operatore: "Giulia Neri",
    status: "finito",
    partecipanti: [
      {
        nome: "Carlo",
        cognome: "Esposito",
        codiceFiscale: "SPSCRL92A01H501Y",
        email: "carlo.esposito@email.com",
        cellulare: "3312345678",
      },
      {
        nome: "Laura",
        cognome: "Ferrari",
        codiceFiscale: "FRRLRA88B21H501W",
        email: "laura.ferrari@email.com",
        cellulare: "3318765432",
      },
      {
        nome: "Paolo",
        cognome: "Ricci",
        codiceFiscale: "RCCPLL95C12H501V",
        email: "paolo.ricci@email.com",
        cellulare: "3319876543",
      },
      {
        nome: "Elisa",
        cognome: "Marchetti",
        codiceFiscale: "MRCLSE94H30H501P",
        email: "elisa.marchetti@email.com",
        cellulare: "3319988776",
      },
    ],
  },
  {
    id: 3,
    location: "Firenze",
    dataInizio: "2025-12-10",
    dataFine: "2025-12-12",
    operatore: "Marco Conti",
    status: "non iniziato",
    partecipanti: [
      {
        nome: "Elena",
        cognome: "Gallo",
        codiceFiscale: "GLLNLN89D34H501T",
        email: "elena.gallo@email.com",
        cellulare: "3391234567",
      },
    ],
  },
  {
    id: 4,
    location: "Torino",
    dataInizio: "2026-01-15",
    dataFine: "2026-01-18",
    operatore: "Sara Bianchi",
    status: "pronto",
    partecipanti: [
      {
        nome: "Davide",
        cognome: "Moretti",
        codiceFiscale: "MRTDVD93E15H501K",
        email: "davide.moretti@email.com",
        cellulare: "3401122334",
      },
      {
        nome: "Chiara",
        cognome: "Romano",
        codiceFiscale: "RMNCHR91F24H501L",
        email: "chiara.romano@email.com",
        cellulare: "3402233445",
      },
      {
        nome: "Stefano",
        cognome: "Russo",
        codiceFiscale: "RSSSTF89A10H501F",
        email: "stefano.russo@email.com",
        cellulare: "3486677889",
      },
      {
        nome: "Federica",
        cognome: "Giordano",
        codiceFiscale: "GRDFRC91E31H501M",
        email: "federica.giordano@email.com",
        cellulare: "3487788990",
      },
      {
        nome: "Giorgio",
        cognome: "Colombo",
        codiceFiscale: "CLMGRG92D21H501B",
        email: "giorgio.colombo@email.com",
        cellulare: "3475566778",
      },
    ],
  },
  {
    id: 5,
    location: "Napoli",
    dataInizio: "2026-02-20",
    dataFine: "2026-02-25",
    operatore: "Alessandro Greco",
    status: "non iniziato",
    partecipanti: [
      {
        nome: "Simone",
        cognome: "De Luca",
        codiceFiscale: "DLCSMN87H45H501R",
        email: "simone.deluca@email.com",
        cellulare: "3453344556",
      },
      {
        nome: "Lucia",
        cognome: "Serra",
        codiceFiscale: "SRRLCU88B20H501Z",
        email: "lucia.serra@email.com",
        cellulare: "3498899001",
      },
    ],
  },
];

export default eventi;